title: "./BUBBLEGUMPOP_NORMANi "
description: @blackgirlscode this is the first repo we made, i made it off the top of my head @nasa-jpl
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker